### ISSUE TITLE
fatal: unable to access 'https://[secure]@[secure]/': Could not resolve host: https

### ISSUE THREAD

**Issue by shaobeichen** [yimogit/metools#1]
文章：使用travis-ci自动部署github上的项目 https://www.cnblogs.com/morang/p/7228488.html

问题：
$ cd ./dist
$ git init
$ git config --global user.name "${U_NAME}"
$ git config --global user.email "${U_EMAIL}"
$ echo "i66.me" > CNAME$ git add .
$ git commit -m "Automatically update from travis-ci"
$ git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
fatal: unable to access 'https://[secure]@[secure]/': Could not resolve host: https
/*-----------------上面出现了https问题，反正目前就是gh-pages显示不了-----------------*/
Done. Your build exited with 0.

代码：https://github.com/LeachZhou/blog/blob/master/.travis.yml

楼主有时间帮我看看，多谢

**Comment by yimogit** [comment]
检查下参数配置对不(看 travis-ci 构建输出的日志)，你现在问题就是提交到gh-pages分支失败了吧。


![image](https://user-images.githubusercontent.com/15975059/40637717-4151c2e2-6339-11e8-93f8-1a77bc152fab.png)

**Comment by shaobeichen** [comment]
好了好了，多谢多谢，2333，被自己蠢哭，仓库地址我没太注意，然后就直接复制github仓库的clone地址了，不小心复制了https://进去，23333

**Comment by yimogit** [comment]
有空我去画下重点。哈哈
