### ISSUE TITLE
Travis  推送不到gh-pages分支，配置和你一样，就是推送不到github上，请问怎么解决？

### ISSUE THREAD

**Issue by q379257013** [yimogit/metools#3]

**Comment by yimogit** [comment]
路径修改了没？
然后就是再检测下环境变量对不对
![image](https://user-images.githubusercontent.com/15975059/61340678-f1083e00-a875-11e9-82ce-91ebf1d6fd70.png)

**Comment by q379257013** [comment]
我按照你的教程来的啊，自动构建能正常跑完，就是没有推送到gh–pages分支上去



发自我的小米手机在 易墨 <notifications@github.com>，2019年7月17日 09:33写道：路径修改了没？

然后就是再检测下环境变量对不对





—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/yimogit/metools/issues/3?email_source=notifications\u0026email_token=AGYD4OMYQQBFYLFL54F4HWDP7ZZHPA5CNFSM4IEJK7LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2CX53I#issuecomment-512065261",

"url": "https://github.com/yimogit/metools/issues/3?email_source=notifications\u0026email_token=AGYD4OMYQQBFYLFL54F4HWDP7ZZHPA5CNFSM4IEJK7LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2CX53I#issuecomment-512065261",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by q379257013** [comment]
分支是手动创建还是自动创建出来的分支？？？？？？？？

**Comment by yimogit** [comment]
会自动创建并覆盖，你看哈是不是token没权限

**Comment by q379257013** [comment]
[![image](https://user-images.githubusercontent.com/28327481/61348797-85819900-a894-11e9-978b-c2ffca3a4157.png)](url)
这个怎么解决呢？

**Comment by q379257013** [comment]
问题已解决！！
